services:
  wikipathways-virtuoso:
    image: openlink/virtuoso-opensource-7:7.2.11
    restart: always
    container_name: wikipathways-virtuoso
    environment:
      - DBA_PASSWORD=dba123
      - SPARQL_UPDATE=false
    ports:
      - "8900:8890"
      - "1134:1111"
  snorql:
    build: .
    restart: always
    container_name: wikipathways-snorql
#    volumes:
#      - /home/MarvinMartens/snorql-extended:/usr/local/apache2/htdocs # To customize the snorql interface, clone the GitHub repo and use its directory as SNORQL_WEB_FILES_DIR
    environment:
      - SNORQL_ENDPOINT=http://localhost:8900/sparql
      - SNORQL_EXAMPLES_REPO=https://github.com/wikipathways/SPARQLQueries
      - SNORQL_TITLE=WikiPathways SNORQL UI
      - DEFAULT_GRAPH=
    ports:
      - "8088:80"
      - "4430:443"
